scripts:
  - &set_android_sdk_location
    name: "Set Android SDK location"
    script: |
      echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
  - &get_app_version
    name: "Get RIA DigiDoc version"
    script: |
      echo "APP_VERSION_NAME=$(grep 'appVersionName=' gradle.properties | cut -d'=' -f 2 | cut -d'-' -f 1)" >> $CM_ENV
  - &read_build_number
    name: Read build number
    script: |
      #!/usr/bin/env bash
      source build_number.env
      echo "Current build number: $BUILD_NUMBER"

  - &increment_build_number
      name: Increment build number
      script: |
        #!/usr/bin/env bash
        source build_number.env
        BUILD_NUMBER=$((BUILD_NUMBER + 1))
        echo "BUILD_NUMBER=$BUILD_NUMBER" > build_number.env
        echo "New build number: $BUILD_NUMBER"

workflows:
  repo-ria:
    name: RIA DigiDoc Android - Repo.ria configuration
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - *set_android_sdk_location
      - *get_app_version
      - *read_build_number
      - *increment_build_number
      - name: Setup Gradle and Build RIA DigiDoc
        script: |
          ./gradlew clean --no-daemon fetchAndPackageDefaultConfiguration -PappVersionName=$APP_VERSION_NAME.$BUILD_NUMBER assemble --debug -PskipGoogleServices
      - name: Rename APK
        script: |
          mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/"RIA_DigiDoc_$APP_VERSION_NAME.$BUILD_NUMBER-unsigned.apk"
    artifacts:
      - app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - marten.rebane@nortal.com
        notify:
          success: true
          failure: true
  live:
    name: RIA DigiDoc Android - Live configuration
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      java: 17
      groups:
        - "live"
    scripts:
      - *set_android_sdk_location
      - *get_app_version
      - *read_build_number
      - *increment_build_number
      - name: Setup Gradle and Build RIA DigiDoc
        script: |
          ./gradlew clean --no-daemon fetchAndPackageDefaultConfiguration -PappVersionName=$APP_VERSION_NAME.$BUILD_NUMBER assemble --debug -PskipGoogleServices
      - name: Rename APK
        script: |
          mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/"RIA_DigiDoc_$APP_VERSION_NAME.$BUILD_NUMBER-unsigned.apk"


    artifacts:
      - app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - marten.rebane@nortal.com
        notify:
          success: true
          failure: true