scripts:
  - &set_android_sdk_location
    name: "Set Android SDK location"
    script: |
      echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
  - &get_app_version
    name: "Get RIA DigiDoc version"
    script: |
      echo "APP_VERSION_NAME=$(grep 'appVersionName=' gradle.properties | cut -d'=' -f 2 | cut -d'-' -f 1)" >> $CM_ENV
  - &get_google_services_json
    name: "Get Google Services configuration"
    script: |
      echo $GOOGLE_SERVICES_JSON | base64 --decode > $CM_BUILD_DIR/app/google-services.json

workflows:
  repo-ria:
    name: RIA DigiDoc Android (MOPP2) - Repo.ria configuration
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      java: 17
      groups:
        - "google_services"
    inputs:
      defaultCentralConfigurationUrl_input:
        description: Default Central Configuration URL
        type: choice
        default: http://repo.ria/config
        options:
          - http://repo.ria/config
          - https://id.eesti.ee
          - https://id.test.eesti.ee
          - http://10.0.25.57/updater
      defaultCentralConfigurationUpdateInterval_input:
        description: Default Central Configuration Update Interval
        type: number
        default: 4
      defaultCentralConfigurationTslUrl_input:
        description: Default Central Configuration TSL URL
        type: choice
        default: http://repo.ria/tsl/trusted-test-mp.xml
        options:
          - http://repo.ria/tsl/trusted-test-mp.xml
          - https://ec.europa.eu/tools/lotl/eu-lotl.xml
          - https://open-eid.github.io/test-TL/tl-mp-test-EE.xml
      memberTsl_input:
        description: TSL member lists
        type: string
        default: "EE;EE_T"
    scripts:
      - *set_android_sdk_location
      - *get_app_version
      - *get_google_services_json
      - name: "Setup TSL files"
        script: |
          if [ ! -d "$CM_BUILD_DIR/app/src/main/assets" ]; then
            cd $CM_BUILD_DIR/app/src/main && { mkdir assets ; cd -; }
            cd $CM_BUILD_DIR/app/src/main/assets && { mkdir tslFiles ; cd -; }
          fi
  
          wget -O $(basename '${{ inputs.defaultCentralConfigurationTslUrl_input }}') -P $CM_BUILD_DIR/app/src/main/assets/tslFiles ${{ inputs.defaultCentralConfigurationTslUrl_input }}
          #wget -O "eu-lotl.xml" -P $CM_BUILD_DIR/app/src/main/assets/tslFiles "https://ec.europa.eu/tools/lotl/eu-lotl.xml"
  
          if [ -f "$CM_BUILD_DIR/app/src/main/assets/tslFiles/eu-lotl.xml" ]; then
            echo "Downloading TSL"
            echo "$CM_BUILD_DIR/app/src/main/assets/tslFiles/$(basename ${{ inputs.defaultCentralConfigurationTslUrl_input }})"
            echo "scripts/TSLXMLDownloader.py --tslFile=$CM_BUILD_DIR/app/src/main/assets/tslFiles/eu-lotl.xml --tslTestFile=$CM_BUILD_DIR/app/src/main/assets/tslFiles/$(basename ${{ inputs.defaultCentralConfigurationTslUrl_input }}) --countries=${{ inputs.memberTsl_input }} --isDevBuild=True"
            python3 scripts/TSLXMLDownloader.py --tslFile="$CM_BUILD_DIR/app/src/main/assets/tslFiles/eu-lotl.xml" --tslTestFile="$CM_BUILD_DIR/app/src/main/assets/tslFiles/$(basename ${{ inputs.defaultCentralConfigurationTslUrl_input }})" --countries="${{ inputs.memberTsl_input }}" --isDevBuild="True"
            echo "Finished downloading TSL"
          else
            python3 scripts/TSLXMLDownloader.py --tslTestFile="$CM_BUILD_DIR/app/src/main/assets/tslFiles/$(basename 'https://ec.europa.eu/tools/lotl/eu-lotl.xml')" --countries="${{ inputs.memberTsl_input }}" --isDevBuild="True"
          fi

          echo "Moving TSLs"
          mv "scripts/TSL/*" "$CM_BUILD_DIR/app/src/main/assets/tslFiles/"
          echo "Done moving TSLs"
          ls -lahtR
      - name: Run tests
        script: |
            ./gradlew clean test --no-daemon
      - name: Build RIA DigiDoc
        script: |
          ./gradlew clean --no-daemon fetchAndPackageDefaultConfiguration --args="${{ inputs.defaultCentralConfigurationUrl_input }} ${{ inputs.defaultCentralConfigurationUpdateInterval_input }}" -PappVersionName=$APP_VERSION_NAME.$PROJECT_BUILD_NUMBER assemble --debug
      - name: Rename and move APK
        script: |
          mkdir app/build/outputs/apk/debug/artifact/
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/artifact/"RIA_DigiDoc_dev_$APP_VERSION_NAME.$PROJECT_BUILD_NUMBER.apk"
    artifacts:
      - app/build/outputs/apk/debug/artifact/*.apk
    publishing:
      email:
        recipients:
          - marten.rebane@nortal.com
        notify:
          success: true
          failure: true
  live:
    name: RIA DigiDoc Android (MOPP2) - Live configuration
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      java: 17
      groups:
        - "live"
    scripts:
      - *set_android_sdk_location
      - *get_app_version
      - name: Setup Gradle and Build RIA DigiDoc
        script: |
          ./gradlew clean --no-daemon fetchAndPackageDefaultConfiguration -PappVersionName=$APP_VERSION_NAME.$PROJECT_BUILD_NUMBER assembleRelease -PskipGoogleServices
      - name: Rename APK
        script: |
          mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/"RIA_DigiDoc_$APP_VERSION_NAME.$PROJECT_BUILD_NUMBER-unsigned.apk"
    artifacts:
      - app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - marten.rebane@nortal.com
        notify:
          success: true
          failure: true
